#!/usr/bin/env python3
# Bake a Launch Kit clock design's image assets into firmware headers for FACE_CUSTOM:
#   - custom_dial.h   : 466x466 RGB565 background, composited exactly like the editor
#                       (cover-fit * zoom, rotated clockwise about the centre).
#   - custom_hands.h  : per-hand baked RGB565+alpha lv_img_dsc sprites (3 bytes/px:
#                       colour lo, colour hi, alpha) that blend_office_sprite() rotates
#                       into the canvas, plus pivot/baseline defines and HAS_* macros.
# Vector hands / a solid background are left to custom_clock.h; this only emits the
# image pieces (HAS_* macro 0 when a piece is absent) so the repo always builds.
#
#   venv/bin/python3 tools/bake_clock_custom.py <spec.json>
#
# Needs Pillow (tools/hands/venv has it). Run via that interpreter.
import sys, json, os
from PIL import Image

CANVAS = 466
CENTER = CANVAS // 2 + (CANVAS % 2) - 1  # 232 for 466? editor centre is 233
CX = CY = 233
MAX_HAND = 220  # clamp a baked hand's longest side; it only needs to reach the rim (~200px).
# Keeps the raw RGB565+alpha array small enough to stay within the device's tight flash
# budget (the sim has no such limit); larger designs with several image hands could
# otherwise overflow the ESP32 partition.


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def hexrgb(s, fallback=(0, 0, 0)):
    s = str(s or "").strip().lstrip("#")
    if len(s) != 6:
        return fallback
    try:
        return (int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16))
    except ValueError:
        return fallback


def bake_dial(bg, out_path):
    if not bg or not bg.get("path") or not os.path.exists(bg["path"]):
        with open(out_path, "w") as f:
            f.write("// Auto-generated by Launch Kit — DO NOT EDIT.\n#pragma once\n#define CUSTOM_HAS_DIAL 0\n")
        return 0
    img = Image.open(bg["path"]).convert("RGBA")
    iw, ih = img.size
    zoom = float(bg.get("zoom") or 1.0)
    s = max(CANVAS / iw, CANVAS / ih) * zoom            # editor drawCover: cover-fit * zoom
    scaled = img.resize((max(1, round(iw * s)), max(1, round(ih * s))), Image.LANCZOS)
    rot = float(bg.get("rotate") or 0.0)
    if rot:
        scaled = scaled.rotate(-rot, resample=Image.BICUBIC, expand=True)  # canvas rotate is clockwise
    base = Image.new("RGBA", (CANVAS, CANVAS), hexrgb(bg.get("color"), (0, 0, 0)) + (255,))
    rw, rh = scaled.size
    base.alpha_composite(scaled, (CX - rw // 2, CY - rh // 2))
    px = base.convert("RGB").load()
    vals = [rgb565(*px[x, y]) for y in range(CANVAS) for x in range(CANVAS)]
    with open(out_path, "w") as f:
        f.write("// Auto-generated by Launch Kit — DO NOT EDIT.\n#pragma once\n#include <stdint.h>\n")
        f.write("#define CUSTOM_HAS_DIAL 1\n")
        f.write(f"static const uint16_t CUSTOM_DIAL[{CANVAS*CANVAS}] = {{\n")
        for i in range(0, len(vals), 16):
            f.write("  " + ",".join(f"0x{v:04X}" for v in vals[i:i + 16]) + ",\n")
        f.write("};\n")
    return CANVAS * CANVAS * 2   # RGB565 flash bytes


def bake_hand(name, hand):
    # Returns (present, text). text is the header fragment for this hand.
    macro = f"CUSTOM_HAS_{name.upper()}_IMG"
    if not hand or not hand.get("path") or not os.path.exists(hand["path"]):
        return 0, f"#define {macro} 0\n"
    img = Image.open(hand["path"]).convert("RGBA")
    scale = float(hand.get("scale") or 1.0)
    w, h = max(1, round(img.width * scale)), max(1, round(img.height * scale))
    if max(w, h) > MAX_HAND:                    # keep the baked array bounded
        k = MAX_HAND / max(w, h)
        w, h = max(1, round(w * k)), max(1, round(h * k))
    img = img.resize((w, h), Image.LANCZOS)
    px = img.load()
    body = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            v = rgb565(r, g, b)
            body.append(v & 0xFF); body.append(v >> 8); body.append(a)
    piv_x = round(float(hand.get("pivotX", 0.5)) * w)
    piv_y = round(float(hand.get("pivotY", 0.5)) * h)
    base = round(float(hand.get("baselineDeg", 0.0)) * 10)
    up = name.upper()
    out = [f"#define {macro} 1"]
    out.append(f"#define CUSTOM_{up}_IMG_W {w}")
    out.append(f"#define CUSTOM_{up}_IMG_H {h}")
    out.append(f"#define CUSTOM_{up}_PIVOT_X {piv_x}")
    out.append(f"#define CUSTOM_{up}_PIVOT_Y {piv_y}")
    out.append(f"#define CUSTOM_{up}_BASELINE_DEG_X10 {base}")
    out.append(f"static const uint8_t CUSTOM_{up}_MAP[{w*h*3}] = {{")
    for i in range(0, len(body), 20):
        out.append("  " + ",".join(str(v) for v in body[i:i + 20]) + ",")
    out.append("};")
    out.append(f"static const lv_img_dsc_t CUSTOM_{up}_IMG = {{")
    out.append(f"  .header = {{ .cf = LV_IMG_CF_TRUE_COLOR_ALPHA, .always_zero = 0, .reserved = 0, .w = {w}, .h = {h} }},")
    out.append(f"  .data_size = {w*h*3}, .data = CUSTOM_{up}_MAP,")
    out.append("};")
    return w * h * 3, "\n".join(out) + "\n"   # RGB565+alpha flash bytes


def main():
    spec = json.load(open(sys.argv[1]))
    out_dir = spec["outDir"]
    sizes = {"dial": bake_dial(spec.get("bg"), os.path.join(out_dir, "custom_dial.h"))}
    hands = spec.get("hands") or {}
    frags = ["// Auto-generated by Launch Kit — DO NOT EDIT.", "#pragma once", "#include <stdint.h>", ""]
    for name in ("hour", "minute", "second"):
        nbytes, text = bake_hand(name, hands.get(name))
        sizes[name] = nbytes
        frags.append(text)
    with open(os.path.join(out_dir, "custom_hands.h"), "w") as f:
        f.write("\n".join(frags))
    sizes["total"] = sum(sizes.values())
    # Machine-readable summary for the push endpoint's flash guardrail.
    print("SIZES " + json.dumps(sizes))


if __name__ == "__main__":
    main()
