// Auto-generated by Launch Kit — DO NOT EDIT.
#pragma once
#include "lvgl.h"
#define CUSTOM_HAS_MENU 1
#define CUSTOM_HAS_MENU_CURRENT 1
#define CUSTOM_MENU_CURRENT_X 233
#define CUSTOM_MENU_CURRENT_Y 233
#define CUSTOM_MENU_CURRENT_COLOR 0x1A1D16
#define CUSTOM_MENU_CURRENT_GLOW 6
#define CUSTOM_MENU_CURRENT_GLOWCOLOR 0x3E350A
#define CUSTOM_MENU_CURRENT_FMT "{name}"
#define CUSTOM_MENU_CURRENT_ALIGN 1
#define CUSTOM_HAS_MENU_PREV 1
#define CUSTOM_MENU_PREV_X 233
#define CUSTOM_MENU_PREV_Y 166
#define CUSTOM_MENU_PREV_COLOR 0x5B542A
#define CUSTOM_MENU_PREV_GLOW 0
#define CUSTOM_MENU_PREV_GLOWCOLOR 0x5F7A6C
#define CUSTOM_MENU_PREV_FMT "{name}"
#define CUSTOM_MENU_PREV_ALIGN 1
#define CUSTOM_HAS_MENU_NEXT 1
#define CUSTOM_MENU_NEXT_X 233
#define CUSTOM_MENU_NEXT_Y 297
#define CUSTOM_MENU_NEXT_COLOR 0x5B542A
#define CUSTOM_MENU_NEXT_GLOW 0
#define CUSTOM_MENU_NEXT_GLOWCOLOR 0x5F7A6C
#define CUSTOM_MENU_NEXT_FMT "{name}"
#define CUSTOM_MENU_NEXT_ALIGN 1
#ifdef __cplusplus
extern "C" {
#endif
extern const lv_font_t custom_menu_font1;
#ifdef __cplusplus
}
#endif
#define CUSTOM_MENU_CURRENT_FONT (&custom_menu_font1)
#define CUSTOM_MENU_PREV_FONT (&lv_font_montserrat_16)
#define CUSTOM_MENU_NEXT_FONT (&lv_font_montserrat_16)
