// Auto-generated by Launch Kit — DO NOT EDIT.
#pragma once
#include "lvgl.h"
#define CUSTOM_HAS_RADAR 1
#define CUSTOM_HAS_RADAR_STYLE 1
#define CUSTOM_SWEEP_ENABLED 1
#define CUSTOM_SWEEP_COLOR 0x39FF14
#define CUSTOM_SWEEP_LEADCOLOR 0xC8FFB0
#define CUSTOM_SWEEP_TRAILDEG 38
#define CUSTOM_SWEEP_OPACITY 60
#define CUSTOM_SWEEP_LENGTH 218
#define CUSTOM_SWEEP_SPEED 13
#define CUSTOM_BLIP_KITE_SHAPE 1
#define CUSTOM_BLIP_SIZE 24
#define CUSTOM_BLIP_KITE_T 15
#define CUSTOM_BLIP_FIXED_COLOR_MODE 1
#define CUSTOM_BLIP_FIXED_COLOR 0xD9D3C1
#define CUSTOM_BLIP_ALT_GROUND 0x888888
#define CUSTOM_BLIP_ALT_LOW 0xFF5A3C
#define CUSTOM_BLIP_ALT_MID 0xFFB23C
#define CUSTOM_BLIP_ALT_HIGH 0xC8FF3C
#define CUSTOM_BLIP_ALT_CRUISE 0x39FF14
#define CUSTOM_BLIP_ALT_JET 0x3CE0FF
#define CUSTOM_BLIP_GLOW 0
#define CUSTOM_BLIP_GLOWCOLOR 0x1A1D16
#define CUSTOM_BLIP_TYPE_IMAGE 1
#define CUSTOM_BLIP_IMAGE_TINT 0
#define CUSTOM_BLIP_IMAGE_BASELINE_DEG 0.0f
#define CUSTOM_SEL_ENABLED 1
#define CUSTOM_SEL_COLOR 0x1A1D16
#define CUSTOM_SEL_WIDTH 1
#define CUSTOM_SEL_DIAMETER 43
#define CUSTOM_SEL_GLOW 13
#define CUSTOM_SEL_GLOWCOLOR 0xD9D3C1
#define CUSTOM_OFFRANGE_ENABLED 0
#define CUSTOM_OFFRANGE_COLOR 0xFF9D3C
#define CUSTOM_OFFRANGE_SIZE 5
#define CUSTOM_CENTER_RADIUS 6
#define CUSTOM_CENTER_COLOR 0xB5442E
#define CUSTOM_CENTER_INNER_RADIUS 2
#define CUSTOM_CENTER_INNER_COLOR 0x6B8F71
// The scope's operational settings used to be welded in here, and are not any more.
// CUSTOM_HAS_RADAR_{RANGE,MAXAC,HIDEGROUND,MINALT,DEADZONE} and their five values moved
// into radar_style.json at THEME_CAPS 34; CUSTOM_HAS_RADAR_HOME and the two coordinates
// beside them were deleted outright rather than moved, because where an Orb is standing
// belongs to whoever owns it and not to whoever drew its face.
//
// What was here shipped Orlando — 28.538300, -81.379200 — in every binary built from this
// tree, along with a 31 km range, five aircraft, a 1250 ft floor and a 60 px dead zone. A
// stranger who flashed it got somebody else's sky and no way to say otherwise. Do not
// reintroduce this block: a value that belongs to one design does not belong in the
// firmware every design is flashed onto. See CUT-18.
#define CUSTOM_RADAR_LAYER_ORDER { 3, 5, 1, 2, 0, 4 }
#define CUSTOM_RADAR_LAYER_ORDER_N 6
#ifdef __cplusplus
extern "C" {
#endif
extern const lv_font_t custom_radar_font1;
extern const lv_font_t custom_radar_font2;
#ifdef __cplusplus
}
#endif
#define CUSTOM_HAS_RTEXT1 1
#define CUSTOM_RTEXT1_FONT (&custom_radar_font1)
#define CUSTOM_RTEXT1_X 104
#define CUSTOM_RTEXT1_Y 123
#define CUSTOM_RTEXT1_COLOR 0xC9A35F
#define CUSTOM_RTEXT1_GLOW 2
#define CUSTOM_RTEXT1_GLOWCOLOR 0x1A1D16
#define CUSTOM_RTEXT1_FMT "{callsign}  {type}"
#define CUSTOM_RTEXT1_ALIGN 0
#define CUSTOM_RTEXT1_CURVED 0
#define CUSTOM_RTEXT1_CURVE_R 0
#define CUSTOM_RTEXT1_ARCDEG 0.00f
#define CUSTOM_HAS_RTEXT2 1
#define CUSTOM_RTEXT2_FONT (&custom_radar_font2)
#define CUSTOM_RTEXT2_X 104
#define CUSTOM_RTEXT2_Y 150
#define CUSTOM_RTEXT2_COLOR 0x1A1D16
#define CUSTOM_RTEXT2_GLOW 1
#define CUSTOM_RTEXT2_GLOWCOLOR 0x000000
#define CUSTOM_RTEXT2_FMT "{alt} ft  ·  {spd} kt  ·  {dist} km"
#define CUSTOM_RTEXT2_ALIGN 0
#define CUSTOM_RTEXT2_CURVED 0
#define CUSTOM_RTEXT2_CURVE_R 0
#define CUSTOM_RTEXT2_ARCDEG 0.00f
#define CUSTOM_HAS_RTEXT3 1
#define CUSTOM_RTEXT3_FONT (&lv_font_montserrat_20)
#define CUSTOM_RTEXT3_X 104
#define CUSTOM_RTEXT3_Y 173
#define CUSTOM_RTEXT3_COLOR 0xD9D3C1
#define CUSTOM_RTEXT3_GLOW 2
#define CUSTOM_RTEXT3_GLOWCOLOR 0x1A1D16
#define CUSTOM_RTEXT3_FMT "{from} -> {to}"
#define CUSTOM_RTEXT3_ALIGN 0
#define CUSTOM_RTEXT3_CURVED 0
#define CUSTOM_RTEXT3_CURVE_R 0
#define CUSTOM_RTEXT3_ARCDEG 0.00f
#define CUSTOM_HAS_RTEXT4 0
