#include "theme_style.h"
#include "theme_sd.h"
#include "theme_select.h"
#include <ArduinoJson.h>
#include <string.h>
#include <stdio.h>
#if !defined(ESP_PLATFORM)
// Desktop simulator: no Serial. This file logs exactly one line (a hand-written theme with
// a second inverted zone), and that line is worth keeping in the sim too, so shim it the
// same way radar_view.cpp already does.
#include <cstdarg>
static struct {
    void println(const char *s) const { puts(s); }
    // printf as well as println: the asset-list and token logging added since this shim was
    // written calls it, and the simulator is where those lines are most worth reading.
    void printf(const char *fmt, ...) const {
        va_list a; va_start(a, fmt); vprintf(fmt, a); va_end(a);
    }
} Serial;
#endif

// Compile-time fallback defaults (and, for a stock/no-design build, the only values
// that ever apply) — same headers each screen's own view already includes.
#include "custom_clock.h"     // CUSTOM_CLOCK.bg
#include "custom_text.h"      // CUSTOM_HAS_TEXT{1,2} / CUSTOM_TEXT{1,2}_*
#include "custom_radar.h"     // CUSTOM_SWEEP_* / CUSTOM_BLIP_* / CUSTOM_SEL_* / CUSTOM_OFFRANGE_* / CUSTOM_CENTER_* / CUSTOM_HAS_RTEXT{1..4} / CUSTOM_RTEXT{n}_*
#include "custom_settings.h"  // CUSTOM_SETTINGS_*
#include "intel.h"           // INTEL_MAX_ITEMS
#include "config.h"          // RADAR_R_OUTER_PX — the dial a dead zone is clamped against
#include "custom_hands.h"    // CUSTOM_HAS_{HOUR,MINUTE,SECOND,STATIC1,STATIC2} / CUSTOM_*_PIVOT_* / CUSTOM_HAND_ORDER
#include "custom_apps.h"     // CUSTOM_APP_* — compiled fallback for the per-theme app roster
#include "custom_menu.h"      // CUSTOM_HAS_MENU_{CURRENT,PREV,NEXT} / CUSTOM_MENU_{...}_*

// custom_apps.h is generated by Launch Kit and names only the apps that existed when it was
// written, so a theme pushed before this one shipped carries no flag for it. Defaulted here
// rather than by editing that file, which the next push would overwrite. An older theme
// therefore gets the app switched on, which is what a stock build does too.
#ifndef CUSTOM_APP_HEADLINES
#define CUSTOM_APP_HEADLINES 1
#endif

namespace theme_style {

namespace {

Clock    s_clock;
Radar    s_radar;
Weather  s_weather;
Ticker   s_ticker;
Menu     s_menu;
Settings s_settings;
Intel    s_intel;
Splash   s_splash;
Apps     s_apps;
Names    s_names;
// The theme's declared asset list (theme.json "assets"). s_assetN == 0 means the theme
// did not declare one, which hasAsset() treats as "allow everything".
// Twenty-four was not enough and had no headroom. A fully dressed theme can ship five
// plates, five overlays, three hands with three shadows, the sweep, the blip, two radar
// stills, the rings, a splash, and up to twenty converted typefaces. Adding the weather
// map's plate and the Stock Ticker's took a real theme past the line, and what happened
// next is the part that matters: the list was silently cut off, so the firmware refused to
// open two files that were sitting on the card, and the only sign was one log line nobody
// was watching. Sixty-four is past anything a theme can currently produce.
constexpr size_t MAX_ASSETS = 64;
char   s_asset[MAX_ASSETS][28] = {};
size_t s_assetN = 0;
uint32_t s_assetsHash = 0;   // theme.json "assetsHash": covers contents, not just names

constexpr size_t MAX_STYLE_JSON_BYTES = 8192;

// Seed every runtime field from the currently-compiled CUSTOM_* macros — exactly
// what each screen drew before this module existed. A JSON style file (if present
// for the active theme) overrides these below, field by field; anything the file
// doesn't set, or no file at all, keeps this compiled default.
void seed_defaults() {
    s_clock = Clock{};
    s_clock.bg = (uint32_t)CUSTOM_CLOCK.bg;
    s_clock.plateFollow = 0;      // static plate unless the theme says otherwise
    s_clock.bgAnim = theme_style::Clock::BgAnim{};   // a still plate unless the theme ships frames
#if CUSTOM_HAS_TEXT1
    s_clock.text1.show = true;
    s_clock.text1.x = CUSTOM_TEXT1_X;
    s_clock.text1.y = CUSTOM_TEXT1_Y;
    s_clock.text1.color = (uint32_t)CUSTOM_TEXT1_COLOR;
    s_clock.text1.glow = CUSTOM_TEXT1_GLOW;
    s_clock.text1.glowColor = (uint32_t)CUSTOM_TEXT1_GLOWCOLOR;
    snprintf(s_clock.text1.fmt, sizeof(s_clock.text1.fmt), "%s", CUSTOM_TEXT1_FMT);
    s_clock.text1.curved = (bool)CUSTOM_TEXT1_CURVED;
    s_clock.text1.curveR = CUSTOM_TEXT1_CURVE_R;
    s_clock.text1.arcDeg = CUSTOM_TEXT1_ARCDEG;
    s_clock.text1.align = CUSTOM_TEXT1_ALIGN;
#endif
#if CUSTOM_HAS_TEXT2
    s_clock.text2.show = true;
    s_clock.text2.x = CUSTOM_TEXT2_X;
    s_clock.text2.y = CUSTOM_TEXT2_Y;
    s_clock.text2.color = (uint32_t)CUSTOM_TEXT2_COLOR;
    s_clock.text2.glow = CUSTOM_TEXT2_GLOW;
    s_clock.text2.glowColor = (uint32_t)CUSTOM_TEXT2_GLOWCOLOR;
    snprintf(s_clock.text2.fmt, sizeof(s_clock.text2.fmt), "%s", CUSTOM_TEXT2_FMT);
    s_clock.text2.curved = (bool)CUSTOM_TEXT2_CURVED;
    s_clock.text2.curveR = CUSTOM_TEXT2_CURVE_R;
    s_clock.text2.arcDeg = CUSTOM_TEXT2_ARCDEG;
    s_clock.text2.align = CUSTOM_TEXT2_ALIGN;
#endif

    // Clock hands (0=hour 1=minute 2=second 3=static1 4=static2). Art, geometry, and the
    // per-hand show gate were all compile-time until now, which is why switching the SD
    // theme swapped the clock plate but left the previous theme's hands sitting on it.
    {
        static const int px[5] = { CUSTOM_HOUR_PIVOT_X, CUSTOM_MINUTE_PIVOT_X, CUSTOM_SECOND_PIVOT_X, CUSTOM_STATIC1_PIVOT_X, CUSTOM_STATIC2_PIVOT_X };
        static const int py[5] = { CUSTOM_HOUR_PIVOT_Y, CUSTOM_MINUTE_PIVOT_Y, CUSTOM_SECOND_PIVOT_Y, CUSTOM_STATIC1_PIVOT_Y, CUSTOM_STATIC2_PIVOT_Y };
        static const int cx[5] = { CUSTOM_HOUR_CENTER_X, CUSTOM_MINUTE_CENTER_X, CUSTOM_SECOND_CENTER_X, CUSTOM_STATIC1_CENTER_X, CUSTOM_STATIC2_CENTER_X };
        static const int cy[5] = { CUSTOM_HOUR_CENTER_Y, CUSTOM_MINUTE_CENTER_Y, CUSTOM_SECOND_CENTER_Y, CUSTOM_STATIC1_CENTER_Y, CUSTOM_STATIC2_CENTER_Y };
        static const int bl[5] = { CUSTOM_HOUR_BLEND, CUSTOM_MINUTE_BLEND, CUSTOM_SECOND_BLEND, CUSTOM_STATIC1_BLEND, CUSTOM_STATIC2_BLEND };
        static const bool has[5] = { (bool)CUSTOM_HAS_HOUR, (bool)CUSTOM_HAS_MINUTE, (bool)CUSTOM_HAS_SECOND, (bool)CUSTOM_HAS_STATIC1, (bool)CUSTOM_HAS_STATIC2 };
        for (int i = 0; i < 5; ++i) {
            s_clock.hand[i].show    = has[i];
            s_clock.hand[i].pivotX  = px[i];
            s_clock.hand[i].pivotY  = py[i];
            s_clock.hand[i].centerX = cx[i];
            s_clock.hand[i].centerY = cy[i];
            s_clock.hand[i].blend   = bl[i];
        }
        static const int ord[] = CUSTOM_HAND_ORDER;
        s_clock.orderN = (CUSTOM_HAND_ORDER_N > 5) ? 5 : CUSTOM_HAND_ORDER_N;
        for (int i = 0; i < s_clock.orderN; ++i) s_clock.order[i] = ord[i];
    }

    // App roster. Settings is not here on purpose: it is a system screen, always present.
    s_apps = Apps{};
    s_names = Names{};      // stock labels; theme.json may relabel any of them
    s_assetsHash = 0;
    s_apps.clock        = (bool)CUSTOM_APP_CLOCK;
    s_apps.flight       = (bool)CUSTOM_APP_FLIGHT;
    s_apps.weather      = (bool)CUSTOM_APP_WEATHER;
    s_apps.surveillance = (bool)CUSTOM_APP_SURVEILLANCE;
    s_apps.headlines    = (bool)CUSTOM_APP_HEADLINES;

    s_radar = Radar{};
    s_radar.sweepEnabled = (bool)CUSTOM_SWEEP_ENABLED;
    s_radar.sweepColor = (uint32_t)CUSTOM_SWEEP_COLOR;
    s_radar.sweepLeadColor = (uint32_t)CUSTOM_SWEEP_LEADCOLOR;
    s_radar.sweepTrailDeg = CUSTOM_SWEEP_TRAILDEG;
    s_radar.sweepOpacity = CUSTOM_SWEEP_OPACITY;
    s_radar.sweepLength = CUSTOM_SWEEP_LENGTH;
    s_radar.sweepSpeed = CUSTOM_SWEEP_SPEED;
    s_radar.blipTypeImage = (bool)CUSTOM_BLIP_TYPE_IMAGE;
    s_radar.blipKiteShape = (bool)CUSTOM_BLIP_KITE_SHAPE;
    s_radar.blipSize = CUSTOM_BLIP_SIZE;
    s_radar.blipKiteT = CUSTOM_BLIP_KITE_T;
    s_radar.blipFixedColorMode = (bool)CUSTOM_BLIP_FIXED_COLOR_MODE;
    s_radar.blipFixedColor = (uint32_t)CUSTOM_BLIP_FIXED_COLOR;
    s_radar.blipAltGround = (uint32_t)CUSTOM_BLIP_ALT_GROUND;
    s_radar.blipAltLow = (uint32_t)CUSTOM_BLIP_ALT_LOW;
    s_radar.blipAltMid = (uint32_t)CUSTOM_BLIP_ALT_MID;
    s_radar.blipAltHigh = (uint32_t)CUSTOM_BLIP_ALT_HIGH;
    s_radar.blipAltCruise = (uint32_t)CUSTOM_BLIP_ALT_CRUISE;
    s_radar.blipAltJet = (uint32_t)CUSTOM_BLIP_ALT_JET;
    s_radar.blipGlow = CUSTOM_BLIP_GLOW;
    s_radar.blipGlowColor = (uint32_t)CUSTOM_BLIP_GLOWCOLOR;
    s_radar.blipImageTint = (bool)CUSTOM_BLIP_IMAGE_TINT;
    s_radar.selEnabled = (bool)CUSTOM_SEL_ENABLED;
    s_radar.selColor = (uint32_t)CUSTOM_SEL_COLOR;
    s_radar.selWidth = CUSTOM_SEL_WIDTH;
    s_radar.selDiameter = CUSTOM_SEL_DIAMETER;
    s_radar.selGlow = CUSTOM_SEL_GLOW;
    s_radar.selGlowColor = (uint32_t)CUSTOM_SEL_GLOWCOLOR;
    s_radar.offRangeEnabled = (bool)CUSTOM_OFFRANGE_ENABLED;
    s_radar.offRangeColor = (uint32_t)CUSTOM_OFFRANGE_COLOR;
    s_radar.offRangeSize = CUSTOM_OFFRANGE_SIZE;
    s_radar.centerRadius = CUSTOM_CENTER_RADIUS;
    s_radar.centerColor = (uint32_t)CUSTOM_CENTER_COLOR;
    s_radar.centerInnerRadius = CUSTOM_CENTER_INNER_RADIUS;
    s_radar.centerInnerColor = (uint32_t)CUSTOM_CENTER_INNER_COLOR;
#if CUSTOM_HAS_RTEXT1
    s_radar.rtext[0].show = true;
    s_radar.rtext[0].x = CUSTOM_RTEXT1_X;
    s_radar.rtext[0].y = CUSTOM_RTEXT1_Y;
    s_radar.rtext[0].color = (uint32_t)CUSTOM_RTEXT1_COLOR;
    s_radar.rtext[0].glow = CUSTOM_RTEXT1_GLOW;
    s_radar.rtext[0].glowColor = (uint32_t)CUSTOM_RTEXT1_GLOWCOLOR;
    snprintf(s_radar.rtext[0].fmt, sizeof(s_radar.rtext[0].fmt), "%s", CUSTOM_RTEXT1_FMT);
    s_radar.rtext[0].align = CUSTOM_RTEXT1_ALIGN;
    s_radar.rtext[0].curved = (bool)CUSTOM_RTEXT1_CURVED;
    s_radar.rtext[0].curveR = CUSTOM_RTEXT1_CURVE_R;
    s_radar.rtext[0].arcDeg = CUSTOM_RTEXT1_ARCDEG;
#endif
#if CUSTOM_HAS_RTEXT2
    s_radar.rtext[1].show = true;
    s_radar.rtext[1].x = CUSTOM_RTEXT2_X;
    s_radar.rtext[1].y = CUSTOM_RTEXT2_Y;
    s_radar.rtext[1].color = (uint32_t)CUSTOM_RTEXT2_COLOR;
    s_radar.rtext[1].glow = CUSTOM_RTEXT2_GLOW;
    s_radar.rtext[1].glowColor = (uint32_t)CUSTOM_RTEXT2_GLOWCOLOR;
    snprintf(s_radar.rtext[1].fmt, sizeof(s_radar.rtext[1].fmt), "%s", CUSTOM_RTEXT2_FMT);
    s_radar.rtext[1].align = CUSTOM_RTEXT2_ALIGN;
    s_radar.rtext[1].curved = (bool)CUSTOM_RTEXT2_CURVED;
    s_radar.rtext[1].curveR = CUSTOM_RTEXT2_CURVE_R;
    s_radar.rtext[1].arcDeg = CUSTOM_RTEXT2_ARCDEG;
#endif
#if CUSTOM_HAS_RTEXT3
    s_radar.rtext[2].show = true;
    s_radar.rtext[2].x = CUSTOM_RTEXT3_X;
    s_radar.rtext[2].y = CUSTOM_RTEXT3_Y;
    s_radar.rtext[2].color = (uint32_t)CUSTOM_RTEXT3_COLOR;
    s_radar.rtext[2].glow = CUSTOM_RTEXT3_GLOW;
    s_radar.rtext[2].glowColor = (uint32_t)CUSTOM_RTEXT3_GLOWCOLOR;
    snprintf(s_radar.rtext[2].fmt, sizeof(s_radar.rtext[2].fmt), "%s", CUSTOM_RTEXT3_FMT);
    s_radar.rtext[2].align = CUSTOM_RTEXT3_ALIGN;
    s_radar.rtext[2].curved = (bool)CUSTOM_RTEXT3_CURVED;
    s_radar.rtext[2].curveR = CUSTOM_RTEXT3_CURVE_R;
    s_radar.rtext[2].arcDeg = CUSTOM_RTEXT3_ARCDEG;
#endif
#if CUSTOM_HAS_RTEXT4
    s_radar.rtext[3].show = true;
    s_radar.rtext[3].x = CUSTOM_RTEXT4_X;
    s_radar.rtext[3].y = CUSTOM_RTEXT4_Y;
    s_radar.rtext[3].color = (uint32_t)CUSTOM_RTEXT4_COLOR;
    s_radar.rtext[3].glow = CUSTOM_RTEXT4_GLOW;
    s_radar.rtext[3].glowColor = (uint32_t)CUSTOM_RTEXT4_GLOWCOLOR;
    snprintf(s_radar.rtext[3].fmt, sizeof(s_radar.rtext[3].fmt), "%s", CUSTOM_RTEXT4_FMT);
    s_radar.rtext[3].align = CUSTOM_RTEXT4_ALIGN;
    s_radar.rtext[3].curved = (bool)CUSTOM_RTEXT4_CURVED;
    s_radar.rtext[3].curveR = CUSTOM_RTEXT4_CURVE_R;
    s_radar.rtext[3].arcDeg = CUSTOM_RTEXT4_ARCDEG;
#endif

    // No CUSTOM_INTEL_* macros to fall back to: this screen never had theme support
    // before THEME_CAPS 9, so there is no prior welded state a theme below that level
    // could be relying on. Compiled defaults ARE the whole fallback.
    s_intel = Intel{};
    s_splash = Splash{};

    s_settings = Settings{};
    s_settings.wheelR = CUSTOM_SETTINGS_WHEEL_R;
    s_settings.wheelRx = CUSTOM_SETTINGS_WHEEL_RX;
    s_settings.wheelStepDeg = CUSTOM_SETTINGS_WHEEL_STEPDEG;
    s_settings.wheelCy = CUSTOM_SETTINGS_WHEEL_CY;
    s_settings.wheelFade = CUSTOM_SETTINGS_WHEEL_FADE;
    s_settings.selColor = (uint32_t)CUSTOM_SETTINGS_SEL_COLOR;
    s_settings.itemColor = (uint32_t)CUSTOM_SETTINGS_ITEM_COLOR;
    s_settings.glow = CUSTOM_SETTINGS_GLOW;
    s_settings.glowColor = (uint32_t)CUSTOM_SETTINGS_GLOWCOLOR;
    s_settings.hlShow = (bool)CUSTOM_SETTINGS_HL_SHOW;
    s_settings.hlColor = (uint32_t)CUSTOM_SETTINGS_HL_COLOR;
    s_settings.hlOpacity = CUSTOM_SETTINGS_HL_OPACITY;
    s_settings.hlW = CUSTOM_SETTINGS_HL_W;
    s_settings.hlH = CUSTOM_SETTINGS_HL_H;
    s_settings.hlRadius = CUSTOM_SETTINGS_HL_RADIUS;
    s_settings.defaultSel = CUSTOM_SETTINGS_DEFAULT_SEL;

    s_menu = Menu{};
#if CUSTOM_HAS_MENU_CURRENT
    s_menu.current.show = true;
    s_menu.current.x = CUSTOM_MENU_CURRENT_X;
    s_menu.current.y = CUSTOM_MENU_CURRENT_Y;
    s_menu.current.color = (uint32_t)CUSTOM_MENU_CURRENT_COLOR;
    s_menu.current.glow = CUSTOM_MENU_CURRENT_GLOW;
    s_menu.current.glowColor = (uint32_t)CUSTOM_MENU_CURRENT_GLOWCOLOR;
    snprintf(s_menu.current.fmt, sizeof(s_menu.current.fmt), "%s", CUSTOM_MENU_CURRENT_FMT);
    s_menu.current.align = CUSTOM_MENU_CURRENT_ALIGN;
#endif
#if CUSTOM_HAS_MENU_PREV
    s_menu.prev.show = true;
    s_menu.prev.x = CUSTOM_MENU_PREV_X;
    s_menu.prev.y = CUSTOM_MENU_PREV_Y;
    s_menu.prev.color = (uint32_t)CUSTOM_MENU_PREV_COLOR;
    s_menu.prev.glow = CUSTOM_MENU_PREV_GLOW;
    s_menu.prev.glowColor = (uint32_t)CUSTOM_MENU_PREV_GLOWCOLOR;
    snprintf(s_menu.prev.fmt, sizeof(s_menu.prev.fmt), "%s", CUSTOM_MENU_PREV_FMT);
    s_menu.prev.align = CUSTOM_MENU_PREV_ALIGN;
#endif
#if CUSTOM_HAS_MENU_NEXT
    s_menu.next.show = true;
    s_menu.next.x = CUSTOM_MENU_NEXT_X;
    s_menu.next.y = CUSTOM_MENU_NEXT_Y;
    s_menu.next.color = (uint32_t)CUSTOM_MENU_NEXT_COLOR;
    s_menu.next.glow = CUSTOM_MENU_NEXT_GLOW;
    s_menu.next.glowColor = (uint32_t)CUSTOM_MENU_NEXT_GLOWCOLOR;
    snprintf(s_menu.next.fmt, sizeof(s_menu.next.fmt), "%s", CUSTOM_MENU_NEXT_FMT);
    s_menu.next.align = CUSTOM_MENU_NEXT_ALIGN;
#endif
}

// 0..255, from a value that may be absent, negative, or 300. Ten opacity fields share this
// rather than each writing its own clamp, because ten hand-written clamps is ten chances to
// differ from the one Studio applies on the other side.
// Same reasoning, for the many integer ranges: one clamp, so it cannot drift from the one
// Orb Studio applies on the other side of the wire.
static int clampi(int v, int lo, int hi) { return v < lo ? lo : (v > hi ? hi : v); }

static int opa_of(JsonVariantConst v, int fallback) {
    if (!v.is<int>()) return fallback;
    const int o = v.as<int>();
    return o < 0 ? 0 : (o > 255 ? 255 : o);
}

// The three keys behind a line of text, in one place because there are four callers now and
// a fifth is a matter of time. THEME_CAPS 33 gave every text control the same two choices,
// and four hand-written copies of the same three reads is how one of them ends up missing a
// clamp. Reading nothing when the theme says nothing is what keeps a design written before
// 33 drawing exactly as it did.
template <typename T>
static void parse_pill(JsonVariantConst j, T &t) {
    if (j["bg"].is<uint32_t>()) t.bg = j["bg"].as<uint32_t>();
    t.bgOpa = opa_of(j["bgOpa"], t.bgOpa);
    if (j["radius"].is<int>()) {
        const int r = j["radius"].as<int>();
        t.radius = r < 0 ? 0 : (r > 40 ? 40 : r);
    }
}

// Merge helpers: only touch a field when the JSON actually has it, so a partial
// file (or a field a given theme never set) leaves the compiled default in place.
void merge_text(JsonVariantConst j, ClockText &t) {
    if (j.isNull()) return;
    if (j["show"].is<bool>()) t.show = j["show"].as<bool>();
    if (j["x"].is<int>()) t.x = j["x"].as<int>();
    if (j["y"].is<int>()) t.y = j["y"].as<int>();
    if (j["color"].is<uint32_t>()) t.color = j["color"].as<uint32_t>();
    t.opa = opa_of(j["opa"], t.opa);
    if (j["glow"].is<int>()) t.glow = j["glow"].as<int>();
    if (j["glowColor"].is<uint32_t>()) t.glowColor = j["glowColor"].as<uint32_t>();
    if (j["fmt"].is<const char *>()) snprintf(t.fmt, sizeof(t.fmt), "%s", j["fmt"].as<const char *>());
    if (j["upper"].is<bool>()) t.upper = j["upper"].as<bool>();   // THEME_CAPS 53
    parse_pill(j, t);
    if (j["curved"].is<bool>()) t.curved = j["curved"].as<bool>();
    if (j["curveR"].is<int>()) t.curveR = j["curveR"].as<int>();
    // int OR float. Studio rounds degrees to a whole number, so the value on the card is `90`
    // and not `90.0`. A check that only accepted a float would leave every "around the dial"
    // control doing nothing, with nothing said about it. Cheap to accept both; expensive to
    // discover later that a slider was ornamental.
    if (j["arcDeg"].is<float>() || j["arcDeg"].is<int>()) t.arcDeg = j["arcDeg"].as<float>();
    if (j["align"].is<int>()) t.align = j["align"].as<int>();
}

void merge_radar_card(JsonVariantConst j, RadarCard &c) {
    if (j.isNull()) return;
    if (j["enabled"].is<bool>()) c.enabled = j["enabled"].as<bool>();
    if (j["typeImage"].is<bool>()) c.typeImage = j["typeImage"].as<bool>();
    if (j["radius"].is<int>()) c.radius = j["radius"].as<int>();
    if (j["w"].is<int>()) c.w = j["w"].as<int>();
    if (j["h"].is<int>()) c.h = j["h"].as<int>();
    if (j["corner"].is<int>()) c.corner = j["corner"].as<int>();
    if (j["color"].is<uint32_t>()) c.color = j["color"].as<uint32_t>();
    if (j["opacity"].is<int>()) c.opacity = j["opacity"].as<int>();
    if (j["borderColor"].is<uint32_t>()) c.borderColor = j["borderColor"].as<uint32_t>();
    if (j["borderWidth"].is<int>()) c.borderWidth = j["borderWidth"].as<int>();
}

// Read a "zones" array into any screen's zone list. Shared because every rule in here is a
// judgement call (a zone with no extent is dropped, at most one inverted zone is honoured)
// and a second copy of a judgement is a second copy that can drift. `who` only names the
// screen in the log line, so a hand-written theme is told WHICH file the problem is in.
static void merge_zones(JsonVariantConst arr, theme_style::Zone *out, int &count, const char *who) {
    if (!arr.is<JsonArrayConst>()) return;
    bool hasInvert = false;
    for (JsonVariantConst z : arr.as<JsonArrayConst>()) {
        if (count >= theme_style::MAX_ZONES) break;
        const bool rect = z["rect"] | false;
        const int  r = z["r"] | 0;
        const int  w = z["w"] | 0;
        const int  h = z["h"] | 0;
        // A zone with no extent masks nothing, so it is dropped rather than shipped as a
        // shape that silently does nothing.
        if (rect ? (w <= 0 || h <= 0) : (r <= 0)) continue;
        const bool invert = z["invert"] | false;
        // At most ONE inverted zone. Inverted means "hide outside me", so two of them
        // intersect: something must be inside both to show, and two that do not overlap hide
        // everything, leaving a screen that looks broken rather than configured. The editors
        // prevent it; this is the backstop for a hand-written theme, and it says so rather
        // than failing quietly.
        if (invert && hasInvert) {
            Serial.printf("[theme] %s: ignoring extra inverted zone, only one is allowed\n", who);
            continue;
        }
        if (invert) hasInvert = true;
        theme_style::Zone &zo = out[count++];
        zo.x      = z["x"] | 233;
        zo.y      = z["y"] | 233;
        zo.r      = r;
        zo.w      = w;
        zo.h      = h;
        zo.rect   = rect;
        zo.invert = invert;
    }
}

void merge_rtext(JsonVariantConst j, RadarText &t) {
    if (j.isNull()) return;
    if (j["show"].is<bool>()) t.show = j["show"].as<bool>();
    if (j["x"].is<int>()) t.x = j["x"].as<int>();
    if (j["y"].is<int>()) t.y = j["y"].as<int>();
    if (j["color"].is<uint32_t>()) t.color = j["color"].as<uint32_t>();
    t.opa = opa_of(j["opa"], t.opa);
    if (j["glow"].is<int>()) t.glow = j["glow"].as<int>();
    if (j["glowColor"].is<uint32_t>()) t.glowColor = j["glowColor"].as<uint32_t>();
    if (j["fmt"].is<const char *>()) snprintf(t.fmt, sizeof(t.fmt), "%s", j["fmt"].as<const char *>());
    if (j["upper"].is<bool>()) t.upper = j["upper"].as<bool>();   // THEME_CAPS 53
    parse_pill(j, t);
    if (j["curved"].is<bool>()) t.curved = j["curved"].as<bool>();
    if (j["curveR"].is<int>()) t.curveR = j["curveR"].as<int>();
    if (j["arcDeg"].is<float>() || j["arcDeg"].is<int>()) t.arcDeg = j["arcDeg"].as<float>();
    if (j["align"].is<int>()) t.align = j["align"].as<int>();
    if (j["onCard"].is<bool>()) t.onCard = j["onCard"].as<bool>();
}

void merge_radar_static(JsonVariantConst j, RadarStatic &s) {
    if (j.isNull()) return;
    if (j["show"].is<bool>()) s.show = j["show"].as<bool>();
    if (j["x"].is<int>()) s.x = j["x"].as<int>();
    if (j["y"].is<int>()) s.y = j["y"].as<int>();
    if (j["opacity"].is<int>()) s.opacity = j["opacity"].as<int>();
    if (j["scale"].is<float>()) s.scale = j["scale"].as<float>();
}

void merge_hand(JsonVariantConst j, Hand &h) {
    if (j.isNull()) return;
    if (j["show"].is<bool>())   h.show    = j["show"].as<bool>();
    if (j["pivotX"].is<int>())  h.pivotX  = j["pivotX"].as<int>();
    if (j["pivotY"].is<int>())  h.pivotY  = j["pivotY"].as<int>();
    if (j["centerX"].is<int>()) h.centerX = j["centerX"].as<int>();
    if (j["centerY"].is<int>()) h.centerY = j["centerY"].as<int>();
    if (j["blend"].is<int>())   h.blend   = j["blend"].as<int>();
}

void merge_menu_text(JsonVariantConst j, MenuText &t) {
    if (j.isNull()) return;
    if (j["show"].is<bool>()) t.show = j["show"].as<bool>();
    if (j["x"].is<int>()) t.x = j["x"].as<int>();
    if (j["y"].is<int>()) t.y = j["y"].as<int>();
    if (j["color"].is<uint32_t>()) t.color = j["color"].as<uint32_t>();
    t.opa = opa_of(j["opa"], t.opa);
    if (j["glow"].is<int>()) t.glow = j["glow"].as<int>();
    if (j["glowColor"].is<uint32_t>()) t.glowColor = j["glowColor"].as<uint32_t>();
    if (j["fmt"].is<const char *>()) snprintf(t.fmt, sizeof(t.fmt), "%s", j["fmt"].as<const char *>());
    // The menu's lines have no plate, so they miss parse_pill and read this themselves.
    if (j["upper"].is<bool>()) t.upper = j["upper"].as<bool>();
    if (j["align"].is<int>()) t.align = j["align"].as<int>();
    if (j["wrapWidth"].is<int>()) t.wrapWidth = j["wrapWidth"].as<int>();
    if (j["lineGap"].is<int>()) t.lineGap = j["lineGap"].as<int>();
    if (j["lineStep"].is<int>()) t.lineStep = j["lineStep"].as<int>();
}

// Reads /themes/<slug>/<name> into `doc`. Returns false (doc left empty) if the
// theme has no such file yet — expected for any theme exported before this
// module existed, or a screen that's never been (re)pushed since.
bool read_style_json(const char *slug, const char *name, JsonDocument &doc) {
    char path[96];
    snprintf(path, sizeof(path), "/themes/%s/%s", slug, name);
    size_t len = 0;
    uint8_t *buf = theme_sd::read_whole(path, len, MAX_STYLE_JSON_BYTES);
    if (!buf) return false;
    const DeserializationError err = deserializeJson(doc, buf, len);
    theme_sd::free(buf);
    return !err;
}

} // namespace

void load() {
    seed_defaults();

    const char *slug = theme_select::activeSlug();
    if (!slug || !slug[0]) return;   // no theme active (stock build) — compiled defaults stand

    {
        JsonDocument doc;
        if (read_style_json(slug, "clock_style.json", doc)) {
            if (doc["windOn"].is<bool>())     s_clock.windOn     = doc["windOn"].as<bool>();
            if (doc["windSecs"].is<int>())    s_clock.windSecs   = doc["windSecs"].as<int>();
            if (doc["windTurns"].is<int>())   s_clock.windTurns  = doc["windTurns"].as<int>();
            if (doc["textOverHands"].is<bool>())     s_clock.textOverHands = doc["textOverHands"].as<bool>();
            if (doc["windImageOn"].is<bool>())       s_clock.windImageOn   = doc["windImageOn"].as<bool>();
            if (doc["windRingShow"].is<bool>())      s_clock.windRingShow  = doc["windRingShow"].as<bool>();
            if (doc["windTitleShow"].is<bool>())     s_clock.windTitleShow = doc["windTitleShow"].as<bool>();
            if (doc["windAskShow"].is<bool>())       s_clock.windAskShow   = doc["windAskShow"].as<bool>();
            if (doc["windCrankOn"].is<bool>())       s_clock.windCrankOn   = doc["windCrankOn"].as<bool>();
            if (doc["windCrankX"].is<int>())         s_clock.windCrankX    = doc["windCrankX"].as<int>();
            if (doc["windCrankY"].is<int>())         s_clock.windCrankY    = doc["windCrankY"].as<int>();
            if (doc["windCrankPX"].is<int>())        s_clock.windCrankPX   = doc["windCrankPX"].as<int>();
            if (doc["windCrankPY"].is<int>())        s_clock.windCrankPY   = doc["windCrankPY"].as<int>();
            if (doc["windCrankRest"].is<int>())      s_clock.windCrankRest = doc["windCrankRest"].as<int>();
            if (doc["secondSweep"].is<bool>())       s_clock.secondSweep = doc["secondSweep"].as<bool>();
            if (doc["secondRailway"].is<bool>())     s_clock.secondRailway = doc["secondRailway"].as<bool>();
            if (doc["windTitleOpa"].is<int>())       s_clock.windTitleOpa  = doc["windTitleOpa"].as<int>();
            if (doc["windAskOpa"].is<int>())         s_clock.windAskOpa    = doc["windAskOpa"].as<int>();
            if (doc["windTurnsOpa"].is<int>())       s_clock.windTurnsOpa  = doc["windTurnsOpa"].as<int>();
            if (doc["windCrankShadowOn"].is<bool>()) s_clock.windCrankShadowOn = doc["windCrankShadowOn"].as<bool>();
            if (doc["windCrankShadowDX"].is<int>())  s_clock.windCrankShadowDX = doc["windCrankShadowDX"].as<int>();
            if (doc["windCrankShadowDY"].is<int>())  s_clock.windCrankShadowDY = doc["windCrankShadowDY"].as<int>();
            if (doc["windBg"].is<uint32_t>())        s_clock.windBg        = doc["windBg"].as<uint32_t>();
            if (doc["windRingTrack"].is<uint32_t>()) s_clock.windRingTrack = doc["windRingTrack"].as<uint32_t>();
            if (doc["windRingFill"].is<uint32_t>())  s_clock.windRingFill  = doc["windRingFill"].as<uint32_t>();
            if (doc["windRingWidth"].is<int>())      s_clock.windRingWidth = doc["windRingWidth"].as<int>();
            if (doc["windRingR"].is<int>())          s_clock.windRingR     = doc["windRingR"].as<int>();
            if (doc["windTitleML"].is<int>())  s_clock.windTitleML = doc["windTitleML"].as<int>();
            if (doc["windTitleMR"].is<int>())  s_clock.windTitleMR = doc["windTitleMR"].as<int>();
            if (doc["windAskML"].is<int>())    s_clock.windAskML   = doc["windAskML"].as<int>();
            if (doc["windAskMR"].is<int>())    s_clock.windAskMR   = doc["windAskMR"].as<int>();
            if (doc["windTurnsML"].is<int>())  s_clock.windTurnsML = doc["windTurnsML"].as<int>();
            if (doc["windTurnsMR"].is<int>())  s_clock.windTurnsMR = doc["windTurnsMR"].as<int>();
            if (doc["windTitle"].is<const char *>())  snprintf(s_clock.windTitle, sizeof(s_clock.windTitle), "%s", doc["windTitle"].as<const char *>());
            if (doc["windTitleSize"].is<int>())      s_clock.windTitleSize = doc["windTitleSize"].as<int>();
            if (doc["windTitleCol"].is<uint32_t>())  s_clock.windTitleCol  = doc["windTitleCol"].as<uint32_t>();
            if (doc["windTitleY"].is<int>())         s_clock.windTitleY    = doc["windTitleY"].as<int>();
            if (doc["windAsk"].is<const char *>())    snprintf(s_clock.windAsk, sizeof(s_clock.windAsk), "%s", doc["windAsk"].as<const char *>());
            if (doc["windAskSize"].is<int>())        s_clock.windAskSize   = doc["windAskSize"].as<int>();
            if (doc["windAskCol"].is<uint32_t>())    s_clock.windAskCol    = doc["windAskCol"].as<uint32_t>();
            if (doc["windAskY"].is<int>())           s_clock.windAskY      = doc["windAskY"].as<int>();
            if (doc["windTurnsShow"].is<bool>())     s_clock.windTurnsShow = doc["windTurnsShow"].as<bool>();
            if (doc["windTurnsSize"].is<int>())      s_clock.windTurnsSize = doc["windTurnsSize"].as<int>();
            if (doc["windTurnsCol"].is<uint32_t>())  s_clock.windTurnsCol  = doc["windTurnsCol"].as<uint32_t>();
            if (doc["windTurnsY"].is<int>())         s_clock.windTurnsY    = doc["windTurnsY"].as<int>();
            if (doc["windSound"].is<bool>())  s_clock.windSound  = doc["windSound"].as<bool>();
            if (doc["windNotice"].is<bool>()) s_clock.windNotice = doc["windNotice"].as<bool>();
            if (doc["bg"].is<uint32_t>()) s_clock.bg = doc["bg"].as<uint32_t>();
            // "plateFollow": which hand the background plate rotates with — 0 none,
            // 1 hour, 2 minute, 3 second. The exported plate PNG carries only its static
            // rotation, so this angle is applied live on top (see clock_view draw_custom).
            if (doc["plateFollow"].is<int>()) s_clock.plateFollow = doc["plateFollow"].as<int>();
            // THEME_CAPS 55, the moving background. Clamped here rather than trusted: the
            // frame count decides how many files are looked for and how much PSRAM the SD
            // path would hold, and a bad number in a shared theme file must not be able to
            // ask for either without limit.
            if (doc["bgAnim"].is<JsonObjectConst>()) {
                JsonObjectConst ba = doc["bgAnim"].as<JsonObjectConst>();
                if (ba["frames"].is<int>()) {
                    const int n = ba["frames"].as<int>();
                    s_clock.bgAnim.frames = n < 0 ? 0 : (n > BG_ANIM_MAX ? BG_ANIM_MAX : n);
                }
                if (ba["fps"].is<int>()) {
                    const int v = ba["fps"].as<int>();
                    s_clock.bgAnim.fps = v < 1 ? 1 : (v > 30 ? 30 : v);
                }
                if (ba["loop"].is<bool>()) s_clock.bgAnim.loop = ba["loop"].as<bool>();
                if (ba["everySec"].is<int>()) {
                    const int v = ba["everySec"].as<int>();
                    s_clock.bgAnim.everySec = v < 1 ? 1 : (v > 86400 ? 86400 : v);
                }
            }
            merge_text(doc["text1"], s_clock.text1);
            merge_text(doc["text2"], s_clock.text2);
            // "hands": { "hour": {...}, "minute": {...}, "second": {...},
            //            "static1": {...}, "static2": {...}, "order": [3,4,0,1,2] }
            JsonVariantConst hands = doc["hands"];
            if (!hands.isNull()) {
                static const char *names[5] = { "hour", "minute", "second", "static1", "static2" };
                for (int i = 0; i < 5; ++i) merge_hand(hands[names[i]], s_clock.hand[i]);
                JsonArrayConst ord = hands["order"].as<JsonArrayConst>();
                if (!ord.isNull() && ord.size() > 0) {
                    int n = 0;
                    for (JsonVariantConst v : ord) {
                        if (n >= 5) break;
                        const int k = v.as<int>();
                        if (k >= 0 && k < 5) s_clock.order[n++] = k;   // ignore junk indices
                    }
                    if (n > 0) s_clock.orderN = n;
                }
                // One light for the whole dial. Absent means off, which is what every
                // theme made before this existed intends.
                JsonVariantConst sh = hands["shadow"];
                if (!sh.isNull()) {
                    s_clock.shadowOn = sh["on"] | false;
                    s_clock.shadowDX = sh["dx"] | 0;
                    s_clock.shadowDY = sh["dy"] | 0;
                }
            }
        }
    }
    {
        // The Stock Ticker's own file, for the same reason every other screen has one.
        JsonDocument doc;
        if (read_style_json(slug, "ticker_style.json", doc)) {
            if (doc["bg"].is<uint32_t>()) s_ticker.bg = doc["bg"].as<uint32_t>();
            if (doc["symbols"].is<const char *>())
                strlcpy(s_ticker.symbols, doc["symbols"].as<const char *>(), sizeof(s_ticker.symbols));
            // Clamped to match Studio, in both directions. Under fifteen seconds is a
            // request every Orb makes four times a minute for a number that has not moved;
            // over fifteen minutes it is not a ticker any more.
            if (doc["pollSeconds"].is<int>())
                s_ticker.pollSeconds = clampi(doc["pollSeconds"].as<int>(), 15, 900);
            if (doc["upColor"].is<uint32_t>())   s_ticker.upColor   = doc["upColor"].as<uint32_t>();
            if (doc["downColor"].is<uint32_t>()) s_ticker.downColor = doc["downColor"].as<uint32_t>();
            if (doc["flatColor"].is<uint32_t>()) s_ticker.flatColor = doc["flatColor"].as<uint32_t>();

            if (doc["nameColor"].is<uint32_t>()) s_ticker.nameColor = doc["nameColor"].as<uint32_t>();
            if (doc["nameSize"].is<int>())  s_ticker.nameSize = doc["nameSize"].as<int>();
            if (doc["nameY"].is<int>())     s_ticker.nameY    = clampi(doc["nameY"].as<int>(), 0, 465);
            if (doc["nameShow"].is<bool>()) s_ticker.nameShow = doc["nameShow"].as<bool>();

            if (doc["priceSize"].is<int>())     s_ticker.priceSize    = doc["priceSize"].as<int>();
            if (doc["priceY"].is<int>())        s_ticker.priceY       = clampi(doc["priceY"].as<int>(), 0, 465);
            if (doc["priceShow"].is<bool>())    s_ticker.priceShow    = doc["priceShow"].as<bool>();
            if (doc["priceColorOn"].is<bool>()) s_ticker.priceColorOn = doc["priceColorOn"].as<bool>();
            if (doc["priceColor"].is<uint32_t>()) s_ticker.priceColor = doc["priceColor"].as<uint32_t>();

            if (doc["changeSize"].is<int>())  s_ticker.changeSize = doc["changeSize"].as<int>();
            if (doc["changeY"].is<int>())     s_ticker.changeY    = clampi(doc["changeY"].as<int>(), 0, 465);
            if (doc["changeShow"].is<bool>()) s_ticker.changeShow = doc["changeShow"].as<bool>();
            if (doc["changePct"].is<bool>())  s_ticker.changePct  = doc["changePct"].as<bool>();

            if (doc["stripShow"].is<bool>())    s_ticker.stripShow  = doc["stripShow"].as<bool>();
            if (doc["stripPlace"].is<int>())
                s_ticker.stripPlace = (uint8_t)clampi(doc["stripPlace"].as<int>(), 0, 2);
            if (doc["stripSize"].is<int>())     s_ticker.stripSize  = doc["stripSize"].as<int>();
            if (doc["stripColor"].is<uint32_t>()) s_ticker.stripColor = doc["stripColor"].as<uint32_t>();
            if (doc["stripOpa"].is<int>())      s_ticker.stripOpa   = clampi(doc["stripOpa"].as<int>(), 0, 255);
            if (doc["stripSpeed"].is<int>())    s_ticker.stripSpeed = clampi(doc["stripSpeed"].as<int>(), 1, 120);
            if (doc["stripY"].is<int>())        s_ticker.stripY     = clampi(doc["stripY"].as<int>(), 0, 465);
            if (doc["stripRadius"].is<int>())   s_ticker.stripRadius = clampi(doc["stripRadius"].as<int>(), 40, 233);
            if (doc["stripAngle"].is<int>())    s_ticker.stripAngle = clampi(doc["stripAngle"].as<int>(), 0, 359);
            if (doc["stripUpDown"].is<bool>())  s_ticker.stripUpDown = doc["stripUpDown"].as<bool>();
        }
    }
    {
        // The weather map's own file. Separate from radar_style.json on purpose: it is a
        // separate app, and the moment the two shared a file somebody's aircraft scope
        // would start changing when they dressed their weather map.
        JsonDocument doc;
        if (read_style_json(slug, "weather_style.json", doc)) {
            if (doc["bg"].is<uint32_t>()) s_weather.bg = doc["bg"].as<uint32_t>();
            if (doc["sweepEnabled"].is<bool>()) s_weather.sweepEnabled = doc["sweepEnabled"].as<bool>();
            if (doc["sweepTypeImage"].is<bool>()) s_weather.sweepTypeImage = doc["sweepTypeImage"].as<bool>();
            if (doc["sweepColor"].is<uint32_t>()) s_weather.sweepColor = doc["sweepColor"].as<uint32_t>();
            if (doc["sweepLeadColor"].is<uint32_t>()) s_weather.sweepLeadColor = doc["sweepLeadColor"].as<uint32_t>();
            if (doc["sweepTrailDeg"].is<int>()) s_weather.sweepTrailDeg = doc["sweepTrailDeg"].as<int>();
            if (doc["sweepOpacity"].is<int>()) s_weather.sweepOpacity = doc["sweepOpacity"].as<int>();
            if (doc["sweepLength"].is<int>()) s_weather.sweepLength = doc["sweepLength"].as<int>();
            if (doc["sweepSpeed"].is<int>()) s_weather.sweepSpeed = doc["sweepSpeed"].as<int>();
            if (doc["sweepTrailWidth"].is<int>()) s_weather.sweepTrailWidth = doc["sweepTrailWidth"].as<int>();
            if (doc["sweepLeadWidth"].is<int>()) s_weather.sweepLeadWidth = doc["sweepLeadWidth"].as<int>();
            if (doc["sweepTrailSteps"].is<int>()) s_weather.sweepTrailSteps = doc["sweepTrailSteps"].as<int>();
            if (doc["ringColor"].is<uint32_t>()) s_weather.ringColor = doc["ringColor"].as<uint32_t>();
            if (doc["ringsEnabled"].is<bool>()) s_weather.ringsEnabled = doc["ringsEnabled"].as<bool>();
            if (doc["roadColor"].is<uint32_t>()) s_weather.roadColor = doc["roadColor"].as<uint32_t>();
            if (doc["roadsEnabled"].is<bool>()) s_weather.roadsEnabled = doc["roadsEnabled"].as<bool>();
            if (doc["coastColor"].is<uint32_t>()) s_weather.coastColor = doc["coastColor"].as<uint32_t>();
            if (doc["coastEnabled"].is<bool>()) s_weather.coastEnabled = doc["coastEnabled"].as<bool>();
            if (doc["ringColorOn"].is<bool>()) s_weather.ringColorOn = doc["ringColorOn"].as<bool>();
            if (doc["ringCount"].is<int>())    s_weather.ringCount   = clampi(doc["ringCount"].as<int>(), 1, 5);
            if (doc["ringWidth"].is<int>())    s_weather.ringWidth   = clampi(doc["ringWidth"].as<int>(), 1, 6);
            if (doc["ringOpacity"].is<int>())  s_weather.ringOpacity = clampi(doc["ringOpacity"].as<int>(), 0, 255);
            if (doc["crosshair"].is<bool>())   s_weather.crosshair   = doc["crosshair"].as<bool>();
            // Four themeable lines, same struct and same reader as the Flight Tracker's, so
            // "curved" and "align" mean one thing across the device. The key is "wtext" and
            // not "rtext" only because the two files are read separately; the shape is
            // identical on purpose.
            JsonVariantConst wtext = doc["wtext"];
            if (wtext.is<JsonArrayConst>()) {
                int i = 0;
                for (JsonVariantConst item : wtext.as<JsonArrayConst>()) {
                    if (i >= 4) break;
                    merge_rtext(item, s_weather.text[i]);
                    i++;
                }
            }
            merge_zones(doc["zones"], s_weather.zones, s_weather.zoneCount, "weather_style.json");
            // The credit's looks, never its existence. Opacity is floored here rather than
            // trusted from the file: this is the one field where a hand-written theme could
            // spell "remove" as "invisible", and the floor is what makes that impossible
            // rather than merely discouraged.
            JsonVariantConst cr = doc["credit"];
            if (!cr.isNull()) {
                theme_style::Weather::Credit &c = s_weather.credit;
                if (cr["x"].is<int>())          c.x      = cr["x"].as<int>();
                if (cr["y"].is<int>())          c.y      = cr["y"].as<int>();
                if (cr["color"].is<uint32_t>()) c.color  = cr["color"].as<uint32_t>();
                parse_pill(cr, c);
                if (cr["align"].is<int>())      c.align  = cr["align"].as<int>();
                if (cr["opa"].is<int>())        c.opa    = cr["opa"].as<int>();
                if (cr["curved"].is<bool>())    c.curved = cr["curved"].as<bool>();
                if (cr["curveR"].is<int>())     c.curveR = cr["curveR"].as<int>();
                if (cr["arcDeg"].is<int>())     c.arcDeg = cr["arcDeg"].as<int>();
                if (c.curveR < 40)  c.curveR = 40;
                if (c.curveR > 233) c.curveR = 233;
                c.arcDeg = ((c.arcDeg % 360) + 360) % 360;
                // Curved wins over the pill rather than the other way round. Orb Studio only
                // offers the curve once the pill is off, so the two can only arrive together
                // in a hand-written theme, and a curve cannot be half-honoured: bending the
                // words and leaving a straight rounded rectangle behind them would look like
                // a fault rather than like a choice.
                if (c.curved) c.bgOpa = 0;
                if (c.opa < theme_style::Weather::CREDIT_MIN_OPA)
                    c.opa = theme_style::Weather::CREDIT_MIN_OPA;
                if (c.opa > 255)   c.opa = 255;
                if (c.bgOpa < 0)   c.bgOpa = 0;
                if (c.bgOpa > 255) c.bgOpa = 255;
                // Kept on the glass. A credit dragged off the edge is a credit removed.
                if (c.x < 30) c.x = 30;  if (c.x > 436) c.x = 436;
                if (c.y < 10) c.y = 10;  if (c.y > 450) c.y = 450;
            }
        }
    }
    {
        JsonDocument doc;
        if (read_style_json(slug, "radar_style.json", doc)) {
            if (doc["sweepEnabled"].is<bool>()) s_radar.sweepEnabled = doc["sweepEnabled"].as<bool>();
            if (doc["sweepTypeImage"].is<bool>()) s_radar.sweepTypeImage = doc["sweepTypeImage"].as<bool>();
            if (doc["sweepColor"].is<uint32_t>()) s_radar.sweepColor = doc["sweepColor"].as<uint32_t>();
            if (doc["sweepLeadColor"].is<uint32_t>()) s_radar.sweepLeadColor = doc["sweepLeadColor"].as<uint32_t>();
            if (doc["sweepTrailDeg"].is<int>()) s_radar.sweepTrailDeg = doc["sweepTrailDeg"].as<int>();
            if (doc["sweepOpacity"].is<int>()) s_radar.sweepOpacity = doc["sweepOpacity"].as<int>();
            if (doc["sweepTrailWidth"].is<int>()) s_radar.sweepTrailWidth = doc["sweepTrailWidth"].as<int>();
            if (doc["sweepLeadWidth"].is<int>()) s_radar.sweepLeadWidth = doc["sweepLeadWidth"].as<int>();
            if (doc["sweepTrailSteps"].is<int>()) s_radar.sweepTrailSteps = doc["sweepTrailSteps"].as<int>();
            if (doc["sweepLength"].is<int>()) s_radar.sweepLength = doc["sweepLength"].as<int>();
            if (doc["sweepSpeed"].is<int>()) s_radar.sweepSpeed = doc["sweepSpeed"].as<int>();
            if (doc["blipEnabled"].is<bool>()) s_radar.blipEnabled = doc["blipEnabled"].as<bool>();
            if (doc["blipTypeImage"].is<bool>()) s_radar.blipTypeImage = doc["blipTypeImage"].as<bool>();
            if (doc["blipRotate"].is<bool>()) s_radar.blipRotate = doc["blipRotate"].as<bool>();
            if (doc["blipKiteShape"].is<bool>()) s_radar.blipKiteShape = doc["blipKiteShape"].as<bool>();
            if (doc["blipSize"].is<int>()) s_radar.blipSize = doc["blipSize"].as<int>();
            if (doc["blipKiteT"].is<int>()) s_radar.blipKiteT = doc["blipKiteT"].as<int>();
            if (doc["blipFixedColorMode"].is<bool>()) s_radar.blipFixedColorMode = doc["blipFixedColorMode"].as<bool>();
            if (doc["blipFixedColor"].is<uint32_t>()) s_radar.blipFixedColor = doc["blipFixedColor"].as<uint32_t>();
            if (doc["blipAltGround"].is<uint32_t>()) s_radar.blipAltGround = doc["blipAltGround"].as<uint32_t>();
            if (doc["blipAltLow"].is<uint32_t>()) s_radar.blipAltLow = doc["blipAltLow"].as<uint32_t>();
            if (doc["blipAltMid"].is<uint32_t>()) s_radar.blipAltMid = doc["blipAltMid"].as<uint32_t>();
            if (doc["blipAltHigh"].is<uint32_t>()) s_radar.blipAltHigh = doc["blipAltHigh"].as<uint32_t>();
            if (doc["blipAltCruise"].is<uint32_t>()) s_radar.blipAltCruise = doc["blipAltCruise"].as<uint32_t>();
            if (doc["blipAltJet"].is<uint32_t>()) s_radar.blipAltJet = doc["blipAltJet"].as<uint32_t>();
            if (doc["blipGlow"].is<int>()) s_radar.blipGlow = doc["blipGlow"].as<int>();
            if (doc["blipGlowColor"].is<uint32_t>()) s_radar.blipGlowColor = doc["blipGlowColor"].as<uint32_t>();
            if (doc["blipImageTint"].is<bool>()) s_radar.blipImageTint = doc["blipImageTint"].as<bool>();
            if (doc["selEnabled"].is<bool>()) s_radar.selEnabled = doc["selEnabled"].as<bool>();
            if (doc["selStyle"].is<int>()) s_radar.selStyle = doc["selStyle"].as<int>();
            if (doc["selColor"].is<uint32_t>()) s_radar.selColor = doc["selColor"].as<uint32_t>();
            s_settings.selOpa = opa_of(doc["selOpa"], s_settings.selOpa);
            if (doc["selWidth"].is<int>()) s_radar.selWidth = doc["selWidth"].as<int>();
            if (doc["selDiameter"].is<int>()) s_radar.selDiameter = doc["selDiameter"].as<int>();
            if (doc["selGlow"].is<int>()) s_radar.selGlow = doc["selGlow"].as<int>();
            if (doc["selGlowColor"].is<uint32_t>()) s_radar.selGlowColor = doc["selGlowColor"].as<uint32_t>();
            if (doc["offRangeEnabled"].is<bool>()) s_radar.offRangeEnabled = doc["offRangeEnabled"].as<bool>();
            if (doc["offRangeColor"].is<uint32_t>()) s_radar.offRangeColor = doc["offRangeColor"].as<uint32_t>();
            if (doc["offRangeSize"].is<int>()) s_radar.offRangeSize = doc["offRangeSize"].as<int>();
            if (doc["centerEnabled"].is<bool>()) s_radar.centerEnabled = doc["centerEnabled"].as<bool>();
            if (doc["centerRadius"].is<int>()) s_radar.centerRadius = doc["centerRadius"].as<int>();
            if (doc["centerColor"].is<uint32_t>()) s_radar.centerColor = doc["centerColor"].as<uint32_t>();
            if (doc["centerInnerRadius"].is<int>()) s_radar.centerInnerRadius = doc["centerInnerRadius"].as<int>();
            if (doc["centerInnerColor"].is<uint32_t>()) s_radar.centerInnerColor = doc["centerInnerColor"].as<uint32_t>();
            JsonVariantConst rtext = doc["rtext"];
            if (rtext.is<JsonArrayConst>()) {
                int i = 0;
                for (JsonVariantConst item : rtext.as<JsonArrayConst>()) {
                    if (i >= 4) break;
                    merge_rtext(item, s_radar.rtext[i]);
                    i++;
                }
            }
            // THEME_CAPS 54. Same merge as the four above, so it inherits every field a
            // text slot has without a second parser to keep in step.
            merge_rtext(doc["locText"], s_radar.locText);
            merge_radar_card(doc["card"], s_radar.card);
            if (doc["mapRoadsOn"].is<bool>()) s_radar.mapRoadsOn = doc["mapRoadsOn"].as<bool>();
            if (doc["ringsPlate"].is<bool>()) s_radar.ringsPlate = doc["ringsPlate"].as<bool>();
            if (doc["mapRoadWidth"].is<int>()) s_radar.mapRoadWidth = doc["mapRoadWidth"].as<int>();
            if (doc["sweepHubOn"].is<bool>()) s_radar.sweepHubOn = doc["sweepHubOn"].as<bool>();
            if (doc["sweepHubColor"].is<uint32_t>()) s_radar.sweepHubColor = doc["sweepHubColor"].as<uint32_t>();
            if (doc["sweepHubRadius"].is<int>()) s_radar.sweepHubRadius = doc["sweepHubRadius"].as<int>();
            if (doc["sweepHubGlow"].is<int>()) s_radar.sweepHubGlow = doc["sweepHubGlow"].as<int>();
            if (doc["sweepHubGlowColor"].is<uint32_t>()) s_radar.sweepHubGlowColor = doc["sweepHubGlowColor"].as<uint32_t>();
            if (doc["mapRoadColor"].is<uint32_t>()) s_radar.mapRoadColor = doc["mapRoadColor"].as<uint32_t>();
            if (doc["mapRoadOpacity"].is<int>()) s_radar.mapRoadOpacity = doc["mapRoadOpacity"].as<int>();
            if (doc["mapAirportsOn"].is<bool>()) s_radar.mapAirportsOn = doc["mapAirportsOn"].as<bool>();
            if (doc["mapAirportColor"].is<uint32_t>()) s_radar.mapAirportColor = doc["mapAirportColor"].as<uint32_t>();
            merge_radar_static(doc["static1"], s_radar.static1);
            merge_radar_static(doc["static2"], s_radar.static2);
            if (doc["overlayEnabled"].is<bool>()) s_radar.overlayEnabled = doc["overlayEnabled"].as<bool>();
            if (doc["overlayColor"].is<uint32_t>()) s_radar.overlayColor = doc["overlayColor"].as<uint32_t>();
            if (doc["overlayOpacity"].is<int>()) s_radar.overlayOpacity = doc["overlayOpacity"].as<int>();
            if (doc["maxAircraft"].is<int>())    s_radar.maxAircraft    = doc["maxAircraft"].as<int>();
            if (doc["minAltFt"].is<int>())       s_radar.minAltFt       = doc["minAltFt"].as<int>();
            // Clamped on the way in: the range divides in geo::projectToScreen, so a zero
            // or a negative from a hand-written theme is a divide rather than a wrong dial.
            if (doc["rangeKm"].is<float>()) {
                const float km = doc["rangeKm"].as<float>();
                if (km > 0.0f) s_radar.rangeKm = km < 1.0f ? 1.0f : (km > 500.0f ? 500.0f : km);
            }
            if (doc["hideGround"].is<bool>())    s_radar.hideGround     = doc["hideGround"].as<bool>() ? 1 : 0;
            // Clamped to the dial rather than trusted. A dead zone wider than the scope
            // hides every contact there is, which looks exactly like a dead feed, and this
            // is the one operational value with no device-side control to undo it with.
            if (doc["deadZonePx"].is<int>())
                s_radar.deadZonePx = clampi(doc["deadZonePx"].as<int>(), 0, (int)RADAR_R_OUTER_PX);
            if (doc["sweepPivotX"].is<int>())    s_radar.sweepPivotX    = doc["sweepPivotX"].as<int>();
            if (doc["sweepPivotY"].is<int>())    s_radar.sweepPivotY    = doc["sweepPivotY"].as<int>();
            if (doc["sweepCenterX"].is<int>())   s_radar.sweepCenterX   = doc["sweepCenterX"].as<int>();
            if (doc["sweepCenterY"].is<int>())   s_radar.sweepCenterY   = doc["sweepCenterY"].as<int>();
            if (doc["blipPivotX"].is<int>())     s_radar.blipPivotX     = doc["blipPivotX"].as<int>();
            if (doc["blipPivotY"].is<int>())     s_radar.blipPivotY     = doc["blipPivotY"].as<int>();
            // "order": [3,4,5,0,1,2] — back-to-front, same kind indices as
            // CUSTOM_RADAR_LAYER_ORDER. Junk indices are ignored rather than trusted;
            // an empty or entirely junk list leaves orderN at 0, which means the welded
            // order stands.
            {
                JsonArrayConst ord = doc["order"].as<JsonArrayConst>();
                if (!ord.isNull() && ord.size() > 0) {
                    int n = 0;
                    for (JsonVariantConst v : ord) {
                        if (n >= 6) break;
                        const int k = v.as<int>();
                        if (k >= 0 && k < 6) s_radar.order[n++] = k;
                    }
                    if (n > 0) s_radar.orderN = n;
                }
            }
            s_radar.zoneCount = 0;
            merge_zones(doc["zones"], s_radar.zones, s_radar.zoneCount, "radar_style.json");
        }
    }
    {
        JsonDocument doc;
        if (read_style_json(slug, "settings_style.json", doc)) {
            if (doc["wheelR"].is<float>()) s_settings.wheelR = doc["wheelR"].as<float>();
            if (doc["wheelRx"].is<float>()) s_settings.wheelRx = doc["wheelRx"].as<float>();
            if (doc["wheelStepDeg"].is<float>()) s_settings.wheelStepDeg = doc["wheelStepDeg"].as<float>();
            if (doc["wheelCy"].is<float>()) s_settings.wheelCy = doc["wheelCy"].as<float>();
            if (doc["wheelFade"].is<float>()) s_settings.wheelFade = doc["wheelFade"].as<float>();
            if (doc["selColor"].is<uint32_t>()) s_settings.selColor = doc["selColor"].as<uint32_t>();
            if (doc["itemColor"].is<uint32_t>()) s_settings.itemColor = doc["itemColor"].as<uint32_t>();
            s_settings.itemOpa = opa_of(doc["itemOpa"], s_settings.itemOpa);
            if (doc["glow"].is<int>()) s_settings.glow = doc["glow"].as<int>();
            if (doc["glowColor"].is<uint32_t>()) s_settings.glowColor = doc["glowColor"].as<uint32_t>();
            // THEME_CAPS 21. Read the shared pair FIRST and seed both halves from it, so a
            // theme written before the split keeps the single glow it asked for on both
            // rows. Then let an explicit per-row value win where one was sent.
            s_settings.selGlow = s_settings.itemGlow = s_settings.glow;
            s_settings.selGlowColor = s_settings.itemGlowColor = s_settings.glowColor;
            if (doc["selGlow"].is<int>()) {
                const int v = doc["selGlow"].as<int>();
                s_settings.selGlow = v < 0 ? 0 : (v > 40 ? 40 : v);
            }
            if (doc["selGlowColor"].is<uint32_t>()) s_settings.selGlowColor = doc["selGlowColor"].as<uint32_t>();
            if (doc["itemGlow"].is<int>()) {
                const int v = doc["itemGlow"].as<int>();
                s_settings.itemGlow = v < 0 ? 0 : (v > 40 ? 40 : v);
            }
            if (doc["itemGlowColor"].is<uint32_t>()) s_settings.itemGlowColor = doc["itemGlowColor"].as<uint32_t>();
            if (doc["hlShow"].is<bool>()) s_settings.hlShow = doc["hlShow"].as<bool>();
            if (doc["hlColor"].is<uint32_t>()) s_settings.hlColor = doc["hlColor"].as<uint32_t>();
            if (doc["hlOpacity"].is<int>()) s_settings.hlOpacity = doc["hlOpacity"].as<int>();
            if (doc["hlW"].is<int>()) s_settings.hlW = doc["hlW"].as<int>();
            if (doc["hlH"].is<int>()) s_settings.hlH = doc["hlH"].as<int>();
            if (doc["hlRadius"].is<int>()) s_settings.hlRadius = doc["hlRadius"].as<int>();
            if (doc["defaultSel"].is<int>()) s_settings.defaultSel = doc["defaultSel"].as<int>();
        }
    }
    {
        // The splash / About screen. Reading this file at all is what tells the firmware
        // that this theme's splash.png was baked WITHOUT the glass, so the overlay is
        // composited on top rather than assumed to be in the picture already. See Splash.
        JsonDocument doc;
        if (read_style_json(slug, "splash_style.json", doc)) {
            s_splash.styled = true;
            // hideable: whether "show" is read at all. False for the version and the credits
            // on purpose, so a file carrying show:false for them changes nothing (UX-028,
            // UX-030); Studio never writes the key for those two either.
            struct { const char *key; SplashText *dst; bool hideable; } items[] = {
                { "version", &s_splash.version, false },
                { "network", &s_splash.network, true  },   // THEME_CAPS 36
                { "credits", &s_splash.credits, false },
                { "theme",   &s_splash.theme,   true  },   // THEME_CAPS 35, hideable at 36
            };
            for (auto &it : items) {
                JsonVariantConst v = doc[it.key];
                if (v.isNull()) continue;
                SplashText &t = *it.dst;
                if (it.hideable && v["show"].is<bool>()) t.show = v["show"].as<bool>();
                if (v["x"].is<int>())         t.x = v["x"].as<int>();
                if (v["y"].is<int>())         t.y = v["y"].as<int>();
                // Clamped to the ladder lv_conf.h actually compiles. Studio clamps to the
                // same range; both directions, per the checklist.
                if (v["size"].is<int>()) {
                    const int z = v["size"].as<int>();
                    t.size = z < 8 ? 8 : (z > 48 ? 48 : z);
                }
                if (v["color"].is<uint32_t>())     t.color = v["color"].as<uint32_t>();
                t.opa = opa_of(v["opa"], t.opa);
                if (v["glow"].is<int>())           t.glow = v["glow"].as<int>();
                if (v["glowColor"].is<uint32_t>()) t.glowColor = v["glowColor"].as<uint32_t>();
                if (v["align"].is<int>()) {
                    const int a = v["align"].as<int>();
                    t.align = a < 0 ? 0 : (a > 2 ? 2 : a);
                }
                if (v["upper"].is<bool>()) t.upper = v["upper"].as<bool>();   // THEME_CAPS 53
                parse_pill(v, t);
                if (v["curved"].is<bool>())  t.curved = v["curved"].as<bool>();
                if (v["curveR"].is<int>())   t.curveR = v["curveR"].as<int>();
                if (v["arcDeg"].is<float>() || v["arcDeg"].is<int>()) t.arcDeg = v["arcDeg"].as<float>();
                // No "show". These three are not the theme's to remove; see Splash.
            }
        }
    }
    {
        JsonDocument doc;
        if (read_style_json(slug, "intel_style.json", doc)) {
            if (doc["bg"].is<uint32_t>()) s_intel.bg = doc["bg"].as<uint32_t>();
            if (doc["titleColor"].is<uint32_t>()) s_intel.titleColor = doc["titleColor"].as<uint32_t>();
            s_intel.titleOpa = opa_of(doc["titleOpa"], s_intel.titleOpa);
            if (doc["textColor"].is<uint32_t>()) s_intel.textColor = doc["textColor"].as<uint32_t>();
            s_intel.textOpa = opa_of(doc["textOpa"], s_intel.textOpa);
            if (doc["sourceColor"].is<uint32_t>()) s_intel.sourceColor = doc["sourceColor"].as<uint32_t>();
            s_intel.sourceOpa = opa_of(doc["sourceOpa"], s_intel.sourceOpa);
            if (doc["staleColor"].is<uint32_t>()) s_intel.staleColor = doc["staleColor"].as<uint32_t>();
            // Browsing marks and the briefing. See THEME_CAPS 19.
            s_intel.selDim = opa_of(doc["selDim"], s_intel.selDim);
            if (doc["selColorOn"].is<bool>()) s_intel.selColorOn = doc["selColorOn"].as<bool>();
            if (doc["selColor"].is<uint32_t>()) s_intel.selColor = doc["selColor"].as<uint32_t>();
            if (doc["selBarOn"].is<bool>()) s_intel.selBarOn = doc["selBarOn"].as<bool>();
            if (doc["selBarColor"].is<uint32_t>()) s_intel.selBarColor = doc["selBarColor"].as<uint32_t>();
            s_intel.selBarOpa = opa_of(doc["selBarOpa"], s_intel.selBarOpa);
            if (doc["selBarRadius"].is<int>()) {
                const int v = doc["selBarRadius"].as<int>();
                s_intel.selBarRadius = v < 0 ? 0 : (v > 60 ? 60 : v);
            }
            if (doc["selBarPadX"].is<int>()) {
                const int v = doc["selBarPadX"].as<int>();
                s_intel.selBarPadX = v < 0 ? 0 : (v > 40 ? 40 : v);
            }
            if (doc["selBarPadY"].is<int>()) {
                const int v = doc["selBarPadY"].as<int>();
                s_intel.selBarPadY = v < 0 ? 0 : (v > 40 ? 40 : v);
            }
            if (doc["briefColorOn"].is<bool>()) s_intel.briefColorOn = doc["briefColorOn"].as<bool>();
            if (doc["briefColor"].is<uint32_t>()) s_intel.briefColor = doc["briefColor"].as<uint32_t>();
            s_intel.briefOpa = opa_of(doc["briefOpa"], s_intel.briefOpa);
            if (doc["briefGap"].is<int>()) {
                const int v = doc["briefGap"].as<int>();
                s_intel.briefGap = v < 0 ? 0 : (v > 40 ? 40 : v);
            }
            if (doc["count"].is<int>()) {
                const int c = doc["count"].as<int>();
                s_intel.count = c < 1 ? 1 : (c > INTEL_MAX_ITEMS ? INTEL_MAX_ITEMS : c);
            }
            if (doc["onScreen"].is<int>()) {
                const int v = doc["onScreen"].as<int>();
                s_intel.onScreen = v < 0 ? 0 : (v > INTEL_MAX_ROWS ? INTEL_MAX_ROWS : v);
            }
            if (doc["topic"].is<const char *>())
                snprintf(s_intel.topic, sizeof(s_intel.topic), "%s", doc["topic"].as<const char *>());
            if (doc["source"].is<const char *>())
                snprintf(s_intel.source, sizeof(s_intel.source), "%s", doc["source"].as<const char *>());
            if (doc["curvedBounds"].is<bool>()) s_intel.curvedBounds = doc["curvedBounds"].as<bool>();
            if (doc["curveRadius"].is<int>()) {
                const int r = doc["curveRadius"].as<int>();
                s_intel.curveRadius = r < 140 ? 140 : (r > 400 ? 400 : r);
            }
            // THEME_CAPS 11, widened at 12. Sizes must land on a compiled Montserrat font:
            // an unknown size snaps to the default rather than to "nearest", because nearest
            // would silently redesign the theme and this codebase refuses rather than
            // guesses. This list mirrors lv_conf.h; adding a size to one means adding it to
            // the other, and to Studio's INTEL_FONT_SIZES, or the three disagree.
            auto fontSizeOk = [](int v) {
                switch (v) {
                    case 12: case 14: case 16: case 18: case 20: case 22: case 24:
                    case 26: case 28: case 32: case 36: case 40: case 44: case 48:
                        return true;
                    default:
                        return false;
                }
            };
            // "left" | "center" | "right", the same three words Studio's control uses.
            // Spelled out rather than sent as a number so a theme file stays readable and a
            // future fourth alignment cannot silently mean something else.
            auto alignFromName = [](const char *v, int fallback) {
                if (!v) return fallback;
                if (!strcmp(v, "left"))   return (int)theme_style::Intel::ALIGN_LEFT;
                if (!strcmp(v, "center")) return (int)theme_style::Intel::ALIGN_CENTER;
                if (!strcmp(v, "right"))  return (int)theme_style::Intel::ALIGN_RIGHT;
                return fallback;
            };
            if (doc["title"].is<const char *>())
                snprintf(s_intel.title, sizeof(s_intel.title), "%s", doc["title"].as<const char *>());
            if (doc["titleShow"].is<bool>()) s_intel.titleShow = doc["titleShow"].as<bool>();
            if (doc["titleSize"].is<int>() && fontSizeOk(doc["titleSize"].as<int>()))
                s_intel.titleSize = doc["titleSize"].as<int>();
            auto clampPos = [](int v) { return v < 0 ? 0 : (v > 466 ? 466 : v); };
            if (doc["titleX"].is<int>()) s_intel.titleX = clampPos(doc["titleX"].as<int>());
            if (doc["titleY"].is<int>()) s_intel.titleY = clampPos(doc["titleY"].as<int>());
            if (doc["textSize"].is<int>()) {
                const int v = doc["textSize"].as<int>();
                s_intel.textSize = fontSizeOk(v) ? v : 0;   // 0 = automatic, and the refusal
            }
            auto clampMargin = [](int v) { return v < 0 ? 0 : (v > 200 ? 200 : v); };
            if (doc["marginLeft"].is<int>())  s_intel.marginLeft  = clampMargin(doc["marginLeft"].as<int>());
            if (doc["marginRight"].is<int>()) s_intel.marginRight = clampMargin(doc["marginRight"].as<int>());
            if (doc["marginTop"].is<int>())    s_intel.marginTop    = clampMargin(doc["marginTop"].as<int>());
            if (doc["marginBottom"].is<int>()) s_intel.marginBottom = clampMargin(doc["marginBottom"].as<int>());
            if (doc["pollMinutes"].is<int>()) {
                const int m = doc["pollMinutes"].as<int>();
                s_intel.pollMinutes = m < 5 ? 5 : (m > 120 ? 120 : m);
            }
            if (doc["lineGap"].is<int>()) {
                const int g = doc["lineGap"].as<int>();
                s_intel.lineGap = g < 0 ? 0 : (g > 24 ? 24 : g);
            }
            if (doc["sourceGap"].is<int>()) {
                const int g = doc["sourceGap"].as<int>();
                s_intel.sourceGap = g < 0 ? 0 : (g > 24 ? 24 : g);
            }
            // Anything unrecognised keeps the current value rather than snapping to a
            // default: a typo in a hand-edited theme should leave the screen as designed,
            // not silently re-centre it.
            if (doc["textAlign"].is<const char *>())
                s_intel.textAlign = alignFromName(doc["textAlign"].as<const char *>(), s_intel.textAlign);
            if (doc["sourceAlign"].is<const char *>())
                s_intel.sourceAlign = alignFromName(doc["sourceAlign"].as<const char *>(), s_intel.sourceAlign);
            if (doc["blockAngle"].is<int>()) {
                const int a = doc["blockAngle"].as<int>();
                s_intel.blockAngle = a < -90 ? -90 : (a > 90 ? 90 : a);
            }
            if (doc["sourceSize"].is<int>() && fontSizeOk(doc["sourceSize"].as<int>()))
                s_intel.sourceSize = doc["sourceSize"].as<int>();
            // THEME_CAPS 49. 0 keeps the credit's face; anything off the ladder is refused
            // back to that rather than snapped, same rule textSize follows.
            if (doc["briefSize"].is<int>()) {
                const int v = doc["briefSize"].as<int>();
                s_intel.briefSize = fontSizeOk(v) ? v : 0;
            }
            if (doc["briefHideTitle"].is<bool>()) s_intel.briefHideTitle = doc["briefHideTitle"].as<bool>();
            // THEME_CAPS 50. Placement pairs, clamped to the panel like titleX/titleY.
            {
                struct P { const char *on; const char *x; const char *y; bool &place; int &px; int &py; };
                P pairs[] = {
                    { "morePlace",      "moreX",      "moreY",      s_intel.morePlace,      s_intel.moreX,      s_intel.moreY      },
                    { "backPlace",      "backX",      "backY",      s_intel.backPlace,      s_intel.backX,      s_intel.backY      },
                    { "briefMorePlace", "briefMoreX", "briefMoreY", s_intel.briefMorePlace, s_intel.briefMoreX, s_intel.briefMoreY },
                };
                for (P &q : pairs) {
                    if (doc[q.on].is<bool>()) q.place = doc[q.on].as<bool>();
                    if (doc[q.x].is<int>()) { const int v = doc[q.x].as<int>(); q.px = v < 0 ? 0 : (v > 466 ? 466 : v); }
                    if (doc[q.y].is<int>()) { const int v = doc[q.y].as<int>(); q.py = v < 0 ? 0 : (v > 466 ? 466 : v); }
                }
            }
            if (doc["ageFmt"].is<const char *>())
                snprintf(s_intel.ageFmt, sizeof(s_intel.ageFmt), "%s", doc["ageFmt"].as<const char *>());
            if (doc["blockOffsetY"].is<int>()) {
                const int o = doc["blockOffsetY"].as<int>();
                s_intel.blockOffsetY = o < -160 ? -160 : (o > 160 ? 160 : o);
            }
            if (doc["ageShow"].is<bool>()) s_intel.ageShow = doc["ageShow"].as<bool>();
            if (doc["ageX"].is<int>()) s_intel.ageX = clampPos(doc["ageX"].as<int>());
            if (doc["ageY"].is<int>()) s_intel.ageY = clampPos(doc["ageY"].as<int>());
            if (doc["ageColor"].is<uint32_t>()) s_intel.ageColor = doc["ageColor"].as<uint32_t>();
            s_intel.ageOpa = opa_of(doc["ageOpa"], s_intel.ageOpa);
            if (doc["ageSize"].is<int>() && fontSizeOk(doc["ageSize"].as<int>()))
                s_intel.ageSize = doc["ageSize"].as<int>();
            if (doc["ageGlow"].is<int>()) {
                const int g = doc["ageGlow"].as<int>();
                s_intel.ageGlow = g < 0 ? 0 : (g > 20 ? 20 : g);
            }
            if (doc["ageGlowColor"].is<uint32_t>()) s_intel.ageGlowColor = doc["ageGlowColor"].as<uint32_t>();
            if (doc["ageCurved"].is<bool>()) s_intel.ageCurved = doc["ageCurved"].as<bool>();
            if (doc["ageBg"].is<uint32_t>()) s_intel.ageBg = doc["ageBg"].as<uint32_t>();
            s_intel.ageBgOpa = opa_of(doc["ageBgOpa"], s_intel.ageBgOpa);
            if (doc["ageRadius"].is<int>()) {
                const int r = doc["ageRadius"].as<int>();
                s_intel.ageRadius = r < 0 ? 0 : (r > 40 ? 40 : r);
            }
            if (doc["ageCurveR"].is<int>()) {
                const int r = doc["ageCurveR"].as<int>();
                s_intel.ageCurveR = r < 40 ? 40 : (r > 233 ? 233 : r);
            }
            if (doc["ageArcDeg"].is<float>()) s_intel.ageArcDeg = doc["ageArcDeg"].as<float>();
        }
    }
    {
        JsonDocument doc;
        if (read_style_json(slug, "menu_style.json", doc)) {
            merge_menu_text(doc["current"], s_menu.current);
            merge_menu_text(doc["prev"], s_menu.prev);
            merge_menu_text(doc["next"], s_menu.next);
        }
    }
    {
        // Theme-level file, not per screen: /themes/<slug>/theme.json
        //   { "apps": { "clock": true, "flight": true, "weather": false,
        //               "intel": false, "surveillance": false } }
        // A theme with no theme.json keeps the compiled roster, so older themes already
        // on the card behave exactly as before. A "settings" key is ignored on purpose:
        // Settings is a system screen and must never be switchable off.
        JsonDocument doc;
        if (read_style_json(slug, "theme.json", doc)) {
            JsonVariantConst a = doc["apps"];
            if (!a.isNull()) {
                if (a["clock"].is<bool>())        s_apps.clock        = a["clock"].as<bool>();
                if (a["flight"].is<bool>())       s_apps.flight       = a["flight"].as<bool>();
                if (a["weather"].is<bool>())      s_apps.weather      = a["weather"].as<bool>();
                if (a["surveillance"].is<bool>()) s_apps.surveillance = a["surveillance"].as<bool>();
                if (a["headlines"].is<bool>())    s_apps.headlines    = a["headlines"].as<bool>();
                if (a["ticker"].is<bool>())       s_apps.ticker       = a["ticker"].as<bool>();
            }
            // Display labels. Purely cosmetic: they never affect which folder is read or
            // which app is which, so a theme can rename Flight Tracker freely.
            if (doc["name"].is<const char *>())
                snprintf(s_names.theme, sizeof(s_names.theme), "%s", doc["name"].as<const char *>());
            if (doc["author"].is<const char *>())
                snprintf(s_names.author, sizeof(s_names.author), "%s", doc["author"].as<const char *>());
            JsonVariantConst nm = doc["names"];
            if (!nm.isNull()) {
                struct { const char *key; char *dst; size_t cap; } map[] = {
                    { "clock",        s_names.clock,        sizeof(s_names.clock)        },
                    { "flight",       s_names.flight,       sizeof(s_names.flight)       },
                    { "weather",      s_names.weather,      sizeof(s_names.weather)      },
                    { "surveillance", s_names.surveillance, sizeof(s_names.surveillance) },
                    { "headlines",    s_names.headlines,    sizeof(s_names.headlines)    },
                    { "ticker",       s_names.ticker,       sizeof(s_names.ticker)       },
                    { "settings",     s_names.settings,     sizeof(s_names.settings)     },
                };
                for (auto &m : map) {
                    JsonVariantConst v = nm[m.key];
                    if (v.is<const char *>() && v.as<const char *>()[0])
                        snprintf(m.dst, m.cap, "%s", v.as<const char *>());
                }
            }
            // "assets": every image this theme actually ships. See hasAsset() in the
            // header for why an undeclared file on the card must be ignored rather than
            // trusted. Absent list -> s_assetN stays 0 -> hasAsset() answers true for
            // everything, which is the old behaviour.
            if (doc["assetsHash"].is<uint32_t>()) s_assetsHash = doc["assetsHash"].as<uint32_t>();
            JsonArrayConst list = doc["assets"].as<JsonArrayConst>();
            if (!list.isNull()) {
                s_assetN = 0;
                for (JsonVariantConst v : list) {
                    const char *n = v.as<const char *>();
                    if (!n || !*n) continue;
                    if (s_assetN >= MAX_ASSETS) {
                        // A TRUNCATED LIST IS WORSE THAN NO LIST. This exists to ignore a
                        // file left behind by an older push; cut short, it starts ignoring
                        // files the current theme genuinely ships, which looks exactly like
                        // the feature that needs them being broken. So fall back to the
                        // behaviour of a theme that declares nothing: allow everything.
                        printf("[theme_style] more than %d assets declared; trusting the card "
                               "instead of a half-read list\n", (int)MAX_ASSETS);
                        s_assetN = 0;
                        break;
                    }
                    strncpy(s_asset[s_assetN], n, sizeof(s_asset[0]) - 1);
                    s_asset[s_assetN][sizeof(s_asset[0]) - 1] = '\0';
                    ++s_assetN;
                }
                printf("[theme_style] theme declares %d asset(s)\n", (int)s_assetN);
            }
        }
    }
}

const Clock &clock() { return s_clock; }
const Radar &radar() { return s_radar; }
const Weather &weather() { return s_weather; }
const Ticker  &ticker()  { return s_ticker;  }
const Menu &menu() { return s_menu; }
const Settings &settings() { return s_settings; }
const Intel &intel() { return s_intel; }
const Splash &splash() { return s_splash; }
const Apps &apps() { return s_apps; }
const Names &names() { return s_names; }

void labelFor(const char *slug, char *out, size_t cap) {
    if (!out || !cap) return;
    snprintf(out, cap, "%s", (slug && slug[0]) ? slug : "");   // slug is the fallback label
    if (!slug || !slug[0]) return;
    JsonDocument doc;
    if (!read_style_json(slug, "theme.json", doc)) return;
    if (doc["name"].is<const char *>() && doc["name"].as<const char *>()[0])
        snprintf(out, cap, "%s", doc["name"].as<const char *>());
}

const char *themeLabel() {
    if (s_names.theme[0]) return s_names.theme;
    const char *slug = theme_select::activeSlug();
    return (slug && slug[0]) ? slug : "Stock";
}

const char *themeAuthor() { return s_names.author; }

uint32_t assetsFingerprint() {
    // Prefer Launch Kit's "assetsHash", which covers the asset CONTENTS. The name-only
    // hash below cannot see a replaced image: swap a background for a different picture
    // of the same name and the fingerprint never moves, so the device keeps serving the
    // previously baked pixels and the new artwork silently never appears.
    if (s_assetsHash) return s_assetsHash;
    if (!s_assetN) return 0;
    uint32_t h = 2166136261u;
    for (size_t i = 0; i < s_assetN; ++i) {
        for (const char *p = s_asset[i]; *p; ++p) { h ^= (uint8_t)*p; h *= 16777619u; }
        h ^= (uint8_t)'\n'; h *= 16777619u;
    }
    return h ? h : 1u;      // never collide with the "no manifest" sentinel
}

bool hasAsset(const char *name) {
    if (!s_assetN) return true;      // theme declared no list: allow everything (old themes)
    if (!name || !*name) return false;
    for (size_t i = 0; i < s_assetN; ++i)
        if (strcmp(s_asset[i], name) == 0) return true;
    return false;
}

} // namespace theme_style
